export const styles = `
.pb-app{position:fixed;inset:0;z-index:1000;overflow:auto;scroll-padding:28px;box-sizing:border-box;color:#edf7f5;background:radial-gradient(ellipse at 35% -15%,#24434e 0,transparent 44%),radial-gradient(ellipse at 95% 75%,#3a2440 0,transparent 38%),#0b121a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}
.pb-app *{box-sizing:border-box}.pb-app .pb-back,.pb-app .pb-mode,.pb-app .pb-button,.pb-app .pb-pattern-card,.pb-app .pb-setting{cursor:pointer;font-family:inherit}.pb-app .pb-gamepad-focus,.pb-app .pb-back:focus-visible,.pb-app .pb-mode:focus-visible,.pb-app .pb-button:focus-visible,.pb-app .pb-pattern-card:focus-visible,.pb-app .pb-setting:focus-visible{outline:3px solid #a8f5ed!important;outline-offset:3px;box-shadow:0 0 0 6px #09282d,0 0 22px #77f3e9!important;position:relative;z-index:2}
.pb-app .pb-disabled{opacity:.42;cursor:not-allowed}.pb-grid-bg{position:fixed;inset:0;pointer-events:none;background-image:linear-gradient(#8bcbd509 1px,transparent 1px),linear-gradient(90deg,#8bcbd509 1px,transparent 1px);background-size:34px 34px;mask-image:linear-gradient(to bottom,#0006,transparent 75%)}
.pb-shell{position:relative;width:min(100%,1700px);min-height:100%;margin:auto;padding:clamp(18px,2.6vw,42px)}
.pb-header{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:20px}.pb-brand{display:flex;align-items:center;gap:15px}.pb-brand-icon{display:grid;grid-template-columns:repeat(5,5px);gap:3px;padding:14px;border:1px solid #69b9bb88;border-radius:15px;background:#142b34;box-shadow:0 0 28px #58dad82a}.pb-brand-icon i{width:5px;height:5px;border-radius:50%;background:#8ef1ed;box-shadow:0 0 7px #77e8e2}.pb-brand-icon i:nth-child(3n){background:#f2a2c5}.pb-brand h1{margin:0;font-size:clamp(28px,3vw,44px);line-height:.95;letter-spacing:-.055em}.pb-brand h1 span{color:#8cebe5}.pb-subtitle{margin:7px 0 0;color:#9fbcc4;font-size:12px;letter-spacing:.08em;text-transform:uppercase;font-weight:800}.pb-header-right{display:flex;align-items:center;gap:12px}.pb-tag{padding:7px 11px;border:1px solid #5b939c;border-radius:6px;color:#a8ebe8;font-size:11px;font-weight:900;letter-spacing:.13em}.pb-back{border:1px solid #597684;background:#1b3440;color:#e7f8f7;padding:11px 17px;border-radius:8px;font-weight:800}.pb-back:hover{background:#294a57}
.pb-topline{height:2px;margin-bottom:22px;background:linear-gradient(90deg,#64e0e2 0,#65a8ff 35%,#d28cff 60%,#f3a264 80%,#ef6e92 100%);opacity:.8;box-shadow:0 0 16px #78d1df7d}
.pb-main{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(325px,.83fr);gap:18px;align-items:start}.pb-stage,.pb-card{background:linear-gradient(150deg,#1c2d38,#13222d 68%);border:1px solid #47626d;border-radius:17px;box-shadow:0 22px 52px #0005;overflow:hidden}
.pb-stage{padding:clamp(16px,2vw,27px)}.pb-stage-heading{display:flex;justify-content:space-between;align-items:start;gap:18px;margin-bottom:15px}.pb-kicker{display:block;color:#8de6e1;font-size:10px;font-weight:900;letter-spacing:.18em;text-transform:uppercase}.pb-stage-heading h2{margin:6px 0 4px;font-size:clamp(20px,2vw,29px);letter-spacing:-.035em}.pb-stage-heading p{margin:0;color:#a4bbc3;font-size:12px;line-height:1.5}.pb-state-chip{flex:none;display:flex;align-items:center;gap:7px;border:1px solid #577b83;background:#1c3943;color:#c5f2e9;border-radius:999px;padding:8px 11px;font-size:11px;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.pb-state-chip i{width:7px;height:7px;background:#8cf3cb;border-radius:50%;box-shadow:0 0 9px #8cf3cb}.pb-state-chip.pb-alert{border-color:#b36f73;color:#ffd3cf;background:#4a2a34}.pb-state-chip.pb-alert i{background:#ff9191}
.pb-matrix-frame{padding:14px;background:linear-gradient(155deg,#303039,#101820 72%);border:1px solid #6a5b55;border-radius:12px;box-shadow:inset 0 1px #ffffff17,0 10px 30px #0006}.pb-matrix-head,.pb-matrix-foot{display:flex;justify-content:space-between;align-items:center;gap:10px;color:#dcae78;font-size:10px;font-weight:900;letter-spacing:.1em}.pb-matrix-head{margin-bottom:11px}.pb-matrix-head strong{font-size:13px;color:#c5f5ed;text-align:right}.pb-matrix-frame canvas{display:block;width:100%;height:auto;aspect-ratio:16/7;border:1px solid #80624a;border-radius:5px;background:#070b12;image-rendering:pixelated;box-shadow:0 0 22px #f4ba5633}.pb-matrix-foot{margin-top:10px;color:#9bb0b8;font-size:9px;letter-spacing:.05em}
.pb-rail-panel{margin-top:16px;padding:15px 17px 17px;border:1px solid #46616c;border-radius:12px;background:#101f2a}.pb-rail-header{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:13px}.pb-rail-header strong{display:block;font-size:13px;color:#eaf6f5}.pb-rail-header span{font-size:10px;color:#9bb5bc;text-transform:uppercase;letter-spacing:.09em;font-weight:800}.pb-rail{display:grid;grid-template-columns:repeat(17,minmax(0,1fr));gap:clamp(2px,.35vw,6px);padding:5px 0}.pb-rail i{display:block;height:clamp(20px,3.1vw,35px);border-radius:3px;background:#28404a;transition:background .045s,box-shadow .045s}.pb-rail-scale{display:flex;justify-content:space-between;margin-top:8px;color:#809da7;font-size:10px;font-weight:800;letter-spacing:.06em}.pb-rail-pattern{display:inline-flex;align-items:center;gap:7px;color:#b9e6e4;font-size:11px;font-weight:800}.pb-rail-pattern:before{content:"";width:6px;height:6px;border-radius:50%;background:#f7ce84;box-shadow:0 0 9px #f7ce84}
.pb-stage-foot{display:flex;justify-content:space-between;gap:12px;margin-top:16px;color:#b9d0d2;font-size:12px}.pb-stage-foot span:last-child{color:#8faeb4;text-align:right}
.pb-side{display:flex;flex-direction:column;gap:14px}.pb-card{padding:18px}.pb-card-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 14px}.pb-card-title h3{font-size:14px;letter-spacing:.04em;text-transform:uppercase;margin:0}.pb-card-title span{font-size:10px;color:#9bb2bc;font-weight:800;letter-spacing:.09em;text-transform:uppercase}
.pb-score-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.pb-score{background:#0d1d27;border:1px solid #3c5967;border-radius:9px;padding:11px 10px;min-width:0}.pb-score small{display:block;color:#9bb7c2;font-size:10px;font-weight:900;letter-spacing:.06em;text-transform:uppercase;white-space:nowrap}.pb-score strong{display:block;margin-top:5px;font:900 clamp(24px,2.7vw,39px)/1.1 ui-monospace,SFMono-Regular,Consolas,monospace;color:#ffdb94;letter-spacing:-.09em}.pb-score:nth-child(2) strong{color:#ffa1c4}.pb-score:nth-child(3) strong{color:#8ce8e1}.pb-level-track{display:flex;align-items:center;gap:6px;margin-top:14px}.pb-level-track i{height:8px;flex:1;border-radius:999px;opacity:.3}.pb-level-track i.pb-current{opacity:1;box-shadow:0 0 11px currentColor}.pb-level-track span{margin-left:7px;color:#bed0d5;font-size:10px;font-weight:800;white-space:nowrap}
.pb-segment{display:flex;gap:4px;background:#0c1e28;border:1px solid #405c68;border-radius:8px;padding:4px}.pb-segment .pb-mode{flex:1;min-width:0;border:0;border-radius:6px;background:transparent;color:#b9cbd1;padding:9px 10px;font-size:12px;font-weight:800;text-align:center}.pb-segment .pb-mode.pb-selected{background:#3a6870;color:#f1fffc}.pb-segment .pb-mode:hover:not(.pb-selected){background:#254451}
.pb-field{display:flex;flex-direction:column;gap:6px;margin-top:12px;color:#c2d6da;font-size:11px;font-weight:800;letter-spacing:.04em}.pb-field>div{width:100%;min-width:0;font-size:12px;letter-spacing:normal}.pb-calibration{display:flex;align-items:center;flex-wrap:wrap;gap:9px;margin-top:8px}.pb-calibration .pb-button{min-height:32px;padding:6px 9px;font-size:11px}.pb-calibration span{color:#a7e8df;font-size:11px;font-weight:700}.pb-control-hint{margin:12px 0 0;color:#9eb8bf;font-size:11px;line-height:1.5}.pb-inline-badges{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.pb-inline-badges span{padding:5px 7px;border:1px solid #48626f;background:#192d37;border-radius:6px;color:#bcd1d4;font-size:10px}.pb-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:15px}.pb-button{border:1px solid #637e87;border-radius:8px;background:#263c49;color:#f1faf9;min-height:39px;padding:9px 13px;font-size:12px;font-weight:900;text-align:center;transition:transform .14s,background .14s}.pb-button:hover:not(.pb-disabled){transform:translateY(-1px);background:#345562}.pb-button.pb-primary{background:#a8eee6;border-color:#a8eee6;color:#09252a}.pb-button.pb-primary:hover:not(.pb-disabled){background:#d0fff7}.pb-button.pb-rose{background:#563449;border-color:#a56983;color:#ffe1ed}.pb-button.pb-quiet{background:#182c37;color:#b5d4d5}
.pb-haptic-result{align-self:center;color:#b7d9d8;font-size:11px;line-height:1.4}.pb-message{border-left:3px solid #87ded8;background:#18353a;color:#d3eae8;padding:9px 12px;border-radius:0 7px 7px 0;font-size:11px;line-height:1.5;margin-top:13px}.pb-message.pb-error{border-color:#ed839b;background:#442a37;color:#ffe1e8}
.pb-patterns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.pb-pattern-card{text-align:left;border:1px solid #46616f;border-radius:8px;padding:10px 11px;color:#ecf7f4;background:#172b36;min-height:72px}.pb-pattern-card:hover:not(.pb-disabled),.pb-pattern-card.pb-current{border-color:#95e7df;background:#294650}.pb-pattern-card strong,.pb-pattern-card span{display:block}.pb-pattern-card strong{font-size:11px;margin-bottom:6px}.pb-pattern-card span{font-size:10px;color:#a8c0c5;line-height:1.35}
.pb-bottom{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(290px,.6fr);gap:18px;margin-top:18px}.pb-diagnostic-row{display:flex;gap:12px;flex-wrap:wrap;align-items:start}.pb-metric{min-width:130px;flex:1;background:#0f202a;border:1px solid #3f5a65;border-radius:9px;padding:11px}.pb-metric small{display:block;color:#9eb7bd;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.pb-metric strong{display:block;margin-top:6px;color:#e9f7f3;font:800 23px/1.1 ui-monospace,SFMono-Regular,Consolas,monospace}.pb-metric em{font-size:11px;font-style:normal;color:#9db9bf}.pb-diagnostics-list{margin-top:11px;font-size:11px;line-height:1.55;color:#b6ccd0}.pb-diagnostics-list b{color:#ecfaf7}.pb-diagnostics-list>div{border-top:1px solid #334e59;padding-top:8px;margin-top:8px}.pb-toggle{display:flex;align-items:start;gap:10px;color:#d3e5e5;font-size:12px;line-height:1.35;margin:11px 0}.pb-toggle input{accent-color:#80e3dc;flex:none;margin-top:2px}.pb-toggle small{display:block;color:#91adb5;font-size:10px;line-height:1.45;margin-top:3px}.pb-footer-note{font-size:10px;line-height:1.5;color:#8da5ad;margin-top:15px}.pb-hardware-warn{padding:10px 12px;border:1px solid #9f7170;background:#422e35;border-radius:8px;color:#ffdbd6;font-size:11px;line-height:1.5;margin-top:12px}
.pb-jokers{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:5px 12px;margin-top:12px;padding:9px 10px;border:1px solid #675e4b;border-radius:8px;background:#302b29;color:#f9d588}.pb-jokers span{font-size:10px;letter-spacing:.08em;font-weight:900}.pb-jokers strong{font-size:20px;letter-spacing:.2em;line-height:1}.pb-jokers i{font-style:normal;opacity:.32}
.pb-setting{display:block;width:100%;margin:8px 0;padding:10px 12px;text-align:left;border:1px solid #47626d;border-radius:8px;background:#182d38;color:#e7f6f4}.pb-setting strong,.pb-setting small{display:block}.pb-setting strong{font-size:12px;letter-spacing:.02em}.pb-setting small{font-size:10px;line-height:1.4;color:#a9c3c8;margin-top:4px}.pb-setting:hover{background:#25424d}
@media(max-width:1040px){.pb-main,.pb-bottom{grid-template-columns:1fr}.pb-side{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.pb-side .pb-card:last-child{grid-column:1/-1}.pb-shell{padding:20px}.pb-stage{padding:20px}}
@media(max-width:680px){.pb-shell{padding:14px}.pb-header{align-items:start}.pb-header-right{align-items:end;flex-direction:column}.pb-brand-icon{padding:9px;gap:2px;grid-template-columns:repeat(5,4px)}.pb-brand-icon i{width:4px;height:4px}.pb-subtitle{font-size:10px}.pb-main{gap:12px}.pb-side{display:flex}.pb-stage{padding:12px}.pb-matrix-frame{padding:8px}.pb-stage-heading{align-items:start}.pb-stage-heading p{display:none}.pb-stage-foot{flex-direction:column}.pb-stage-foot span:last-child{text-align:left}.pb-score-grid{gap:5px}.pb-score{padding:8px 6px}.pb-score small{font-size:8px}.pb-score strong{font-size:25px}.pb-matrix-head{font-size:8px}.pb-matrix-head strong{font-size:10px}.pb-matrix-foot{font-size:7px}.pb-rail-panel{padding:10px}.pb-rail i{height:20px}.pb-patterns{gap:5px}.pb-pattern-card{padding:8px}.pb-pattern-card strong{font-size:10px}}
@media(prefers-reduced-motion:reduce){.pb-button,.pb-rail i{transition:none}}
`;
